### DISCUSSION TITLE
Serialize date from string "yyyy-MM-dd"?

### DISCUSSION THREAD

**Discussion by Zerowalker** [time-rs/time#694] [Question] [answered]
Is it possible to achieve this?

Here's an example (that doesn't work):
```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct Foo {
    pub from: time::Date,
    pub to: time::Date,
}

let json = "{ \"from\": \"2024-01-01\", \"to\": \"2024-01-02\"}";
let q: Foo= serde_json::from_str(json).unwrap();
```

**Comment by jhpratt** [comment]
What is your `Cargo.toml`?

**Reply by Zerowalker** [reply]
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = [] }
time = { version = "0.3", features = ["std", "serde"] }
```
