### ISSUE TITLE
Upgrading to rand 0.8

### ISSUE THREAD

**Issue by dmit** [time-rs/time#298]
A new version of the [`rand`](https://github.com/rust-random/rand/blob/master/CHANGELOG.md#080---2020-12-18) crate has been released. While the changes needed to upgrade `time` itself are trivial, `quickcheck` still depends on `rand` 0.7.3 and it is unclear when a new version will be released (although there's already a PR at BurntSushi/quickcheck#264).

It is technically possible to rely on both 0.7.3 (for `quickcheck`) and 0.8.0 (for everything else) by doing something like this:
```toml
[dependencies]
rand = { version = "0.8.0", optional = true, default-features = false }
rand-07 = { package = "rand", version = "0.7.3", optional = true, default-features = false }

[features]
quickcheck = ["quickcheck-dep", "rand-07", "std"]
```
Although it's not very pretty. I'll submit a PR to give a better idea of what the changes look like.

MSRV is not affected, since `rand` 0.8 supports Rust >=1.36.
