### ISSUE TITLE
no_std build error

### ISSUE THREAD

**Issue by reneherrero** [time-rs/time#349]
Are no_std builds working?

I have `time = { version="0.3.2", default-features = false }` in my toml and getting the following :
```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7m-none-eabi` target may not support the standard library
  = note: `std` is required by `time` because it does not declare `#![no_std]`
```

Am I missing anything?

**Comment by jhpratt** [comment]
Hmm...I _can_ reproduce this locally, but at the same time it works fine in CI: https://github.com/time-rs/time/runs/3571089762?check_suite_focus=true#step:6:1

`#![no_std]` is definitely declared, too: https://github.com/time-rs/time/blob/40d433eae94c81598cec066d838e689401e67576/src/lib.rs#L79

Have you checked to see if this behavior is new with the 1.55 release?

**Comment by jhpratt** [comment]
Actually, just confirmed this works as expected. The error is objectively wrong and imo should have an issue filed for it with a minimal example. The issue is that _the binary_ does not declare `#![no_std]`.

`Cargo.toml`:

```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
time = { version = "0.3.2", default-features = false }
```

`main.rs`:

```rust
#![no_std]

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}

fn main() {}
```

Running `cargo check --target thumbv7em-none-eabi` succeeds as expected.
